export const createImage = async (pixelData, meta) => {
  const img = {};
  img.transferSyntax = "unknown";
  img.bitsAllocated = "unknown";
  img.rows = meta?.["rows"];
  img.columns = meta?.["columns"];
  img.rowPixelSpacing = meta?.["spacing"]?.[1];
  img.columnPixelSpacing = meta?.["spacing"]?.[0];
  img.slope = meta?.["rescaleSlope"];
  img.intercept = meta?.["rescaleIntercept"];
  img.color = "unknown";
  img.minPixelValue = meta?.["minPixelValue"];
  img.maxPixelValue = meta?.["maxPixelValue"];
  img.windowCenter = meta?.["windowCenter"];
  img.windowWidth = meta?.["windowWidth"];
  img.imageOrientationPatient = meta?.["direction"];
  img.imagePositionPatient = meta?.["origin"];
  img.sliceThickness = meta?.["SliceThickness"];
  img.spacingBetweenSlices = meta?.["spacing"]?.[2];
  img.studyDate = meta?.["studyDate"];
  img.studyTime = meta?.["studyTime"];
  img.seriesNum = meta?.["seriesNumber"];
  img.accessionNumber = "unknown";
  img.patientId = meta?.["patientID"];
  img.patientName = meta?.["patientName"];
  img.patientSex = meta?.["patientSex"];
  img.patientAge = meta?.["patientAge"];
  img.studyID = meta?.["studyID"];
  img.seriesId = meta?.["seriesInstanceUID"];
  img.pixelData = pixelData;
  return img;
};
